### ISSUE TITLE
Could not sanitize molecule ending on line 68

### ISSUE THREAD

**Issue by xiaoboy185** [mordred-descriptor/mordred#105]
Dear mordred users

when i run the following command line:
python -m mordred -t sdf clusters.sdf -o clusters.csv

the error is 
[10:58:35] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:58:35] ERROR: Could not sanitize molecule ending on line 68
[10:58:35] ERROR: Explicit valence for atom # 11 B, 4, is greater than permitted
WARNING:root:mol read failure: clusters

The following is the sdf file

clusters
 OpenBabel01042310313D

 30 33  0  0  1  0  0  0  0  0999 V2000
   -1.5093   -3.2766    0.6653 O   0  0  0  0  0  1  0  0  0  0  0  0
   -1.2712   -2.1184    0.4200 C   0  0  2  0  0  3  0  0  0  0  0  0
    0.0521   -1.6942    0.3007 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.4728   -0.4370    0.0305 C   0  0  2  0  0  3  0  0  0  0  0  0
   -0.4104    0.5272   -0.1484 N   0  0  1  0  0  0  0  0  0  0  0  0
   -1.7723    0.2605   -0.0605 C   0  0  2  0  0  3  0  0  0  0  0  0
   -2.7232    1.2681   -0.2460 C   0  0  0  0  0  3  0  0  0  0  0  0
   -4.0685    0.9799   -0.1540 C   0  0  0  0  0  3  0  0  0  0  0  0
   -4.5139   -0.3091    0.1234 C   0  0  0  0  0  3  0  0  0  0  0  0
   -3.5936   -1.3146    0.3094 C   0  0  0  0  0  3  0  0  0  0  0  0
   -2.2277   -1.0413    0.2199 C   0  0  2  0  0  3  0  0  0  0  0  0
    0.0653    2.0379   -0.4730 B   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4754    2.3781   -1.6869 F   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4206    2.8370    0.5306 F   0  0  0  0  0  0  0  0  0  0  0  0
    1.5032    2.1309   -0.5280 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.3278    1.1339   -0.3398 C   0  0  2  0  0  3  0  0  0  0  0  0
    3.7066    1.3956   -0.4267 C   0  0  0  0  0  3  0  0  0  0  0  0
    4.6246    0.3948   -0.2401 C   0  0  0  0  0  3  0  0  0  0  0  0
    4.2009   -0.9055    0.0405 C   0  0  0  0  0  3  0  0  0  0  0  0
    2.8612   -1.1854    0.1302 C   0  0  0  0  0  3  0  0  0  0  0  0
    1.8909   -0.1819   -0.0558 C   0  0  2  0  0  3  0  0  0  0  0  0
    0.7462   -2.4201    0.4344 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4090    2.2729   -0.4615 H   0  0  0  0  0  0  0  0  0  0  0  0
   -4.7852    1.7733   -0.3009 H   0  0  0  0  0  0  0  0  0  0  0  0
   -5.5704   -0.5168    0.1918 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.8909   -2.3292    0.5265 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.0066    2.4078   -0.6444 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.6798    0.6103   -0.3096 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.9263   -1.6901    0.1868 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.5714   -2.2028    0.3489 H   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  1  0  0  0
  3  2  1  0  0  0  0
  3 22  1  0  0  0  0
  4  3  1  6  0  0  0
  5 12  1  1  0  0  0
  5  6  1  0  0  0  0
  5  4  1  0  0  0  0
  6  7  1  1  0  0  0
  6 11  1  0  0  0  0
  7  8  1  0  0  0  0
  8  9  1  0  0  0  0
  9 25  1  0  0  0  0
  9 10  1  0  0  0  0
 10 26  1  0  0  0  0
 11 10  1  1  0  0  0
 11  2  1  0  0  0  0
 12 14  1  0  0  0  0
 13 12  1  0  0  0  0
 15 12  1  0  0  0  0
 16 15  1  6  0  0  0
 16 21  1  0  0  0  0
 17 16  1  0  0  0  0
 17 18  1  0  0  0  0
 18 19  1  0  0  0  0
 19 20  1  0  0  0  0
 19 29  1  0  0  0  0
 20 30  1  0  0  0  0
 21  4  1  0  0  0  0
 21 20  1  6  0  0  0
 23  7  1  0  0  0  0
 24  8  1  0  0  0  0
 27 17  1  0  0  0  0
 28 18  1  0  0  0  0
M  END
$$$$

**Comment by tobigithub** [comment]
@xiaoboy185 Boron is valence 3, so your molecule is charged. Can you add the SMILES code for the molecule? Because in the way you posted the SD you posted it is broken.

http://www.cheminfo.org/Chemistry/Cheminformatics/FormatConverter/index.html

**Comment by xiaoboy185** [comment]
Dear tobigithub
Thanks very much for your message.

The smile code for this molecule is O=c1[nH]c2[n+](c3ccccc13)[B-](F)(F)Oc1ccccc1-2
To generate the descriptor by using this smile code, the results are alright:
mol = Chem.MolFromSmiles('O=c1[nH]c2[n+](c3ccccc13)[B-](F)(F)Oc1ccccc1-2')
mol=Chem.AddHs(mol)
AllChem.EmbedMolecule(mol,randomSeed=1)
calc = Calculator(descriptors,ignore_3D=True)
df1=calc(mol)

While, I want to optimiaze this structure firstly, and then generate the descriptors
My procedure is as following:
(1) The xyz file of this molecule is obtained by using this smile code via rdkit. (in this step, the charge information is lost)
(2) the structure optimization was carried out by using xtb, then the 3D .xyz structure of this molecule is obtained. 
(3) the openbabel is used to convert the above 3D .xyz file to .sdf file
(4) mordred is used to generate descriptors.
In this sdf file, there is no information about the charges on B and N atom. I do not know how to add the charges in the .sdf files.

I am looking forward to your message.

Thanks in advance.

**Comment by tobigithub** [comment]
@xiaoboy185 mm, something completely different from the SDF you showed earlier, the SMILES code is not a standard SMILES check here: https://marvinjs-demo.chemaxon.com/latest/demo.html

"O=c1[nH]c2n+B-(F)Oc1ccccc1-2"

Can you just attach the SDF and XYZ as file via drag and drop?

**Comment by xiaoboy185** [comment]
Dear tobigithub

Thanks for you reply.
The smile code with standard form is 
[H]c1c([H])c([H])c2c(c1[H])O[B-](F)(F)[n+]1c-2n([H])c(=O)c2c([H])c([H])c([H])c([H])c21

The corresponding xyz and sdf files are attached.

Thanks
[test.zip](https://github.com/mordred-descriptor/mordred/files/10357930/test.zip)

**Comment by tobigithub** [comment]
Well, so Boron valence=4 thats ok, but there is also a carbon with valence=3.

Is that where you want to have the negative charge? Or is the whole molecule positively charged, then you need to correct the valence state for the carbon somehow. Anyway, there is a bond missing, you could make the nitrogen positive and add a double bond ([H]N1C(=O)C2=C(C([H])=C([H])C([H])=C2[H])[N+]2=C1C1=C(O[B-]2(F)F)C([H])=C([H])C([H])=C1[H]) 

I think you have to fix your molecule first and then check again. The question is if the fix is actually the molecule you want or something else. With the proposed charged (not sure of that is feasible) Mordred will calculate. So its not a Mordred issue, i think although maybe it does not cover the specific atom types and valence states for Boron. See attached SDF, upload here: https://mordred.phs.osaka-u.ac.jp/

![image](https://user-images.githubusercontent.com/2569565/210950074-dc0e455d-a2ac-4f46-a11d-b61d16a89197.png)


![image](https://user-images.githubusercontent.com/2569565/210950355-15a9525c-5ea9-4110-812a-9bee0dfba0c4.png)

![image](https://user-images.githubusercontent.com/2569565/210951274-7da4a2e3-d123-447c-adf7-1983f0ad2064.png)

Fixed molecule mordred:
![image](https://user-images.githubusercontent.com/2569565/210951679-d2f50e26-510b-4cb1-a2e2-174f4563b04c.png)

Once thats done, it will calculate.

![image](https://user-images.githubusercontent.com/2569565/210951821-9d2cd0d2-ad6a-4cbc-90a2-0cbf0558cbd5.png)

**Comment by tobigithub** [comment]
fixed sdf
````
test.xyz
  Mrv2219 01062307253D          

 30 33  0  0  1  0            999 V2000
   -1.7167   -3.2073    0.3418 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3384   -2.0314    0.2074 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0058   -1.7858    0.1462 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4035    0.4999   -0.0851 N   0  3  0  0  0  0  0  0  0  0  0  0
   -1.7408    0.2745   -0.0261 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6572    1.3022   -0.1107 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.0105    1.0569   -0.0491 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.5221   -0.2072    0.0981 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6128   -1.2376    0.1832 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2414   -0.9986    0.1218 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0417    1.9307   -0.2497 B   0  5  1  0  0  0  0  0  0  0  0  0
   -0.9506    3.1727   -1.4915 F   0  0  0  0  0  0  0  0  0  0  0  0
    0.4422    3.1659    0.8914 F   0  0  0  0  0  0  0  0  0  0  0  0
    1.5210    2.0762   -0.2994 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.3843    1.0225   -0.2106 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7485    1.2891   -0.2734 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6508    0.2537   -0.1875 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.1704   -1.0309   -0.0403 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.7913   -1.2908    0.0221 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.9006   -0.2586   -0.0637 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6672   -2.5465    0.2094 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3054    2.3271   -0.2284 H   0  0  0  0  0  0  0  0  0  0  0  0
   -4.7033    1.8955   -0.1196 H   0  0  0  0  0  0  0  0  0  0  0  0
   -5.5967   -0.3839    0.1451 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.9835   -2.2559    0.3007 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.1108    2.3105   -0.3900 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.7225    0.4468   -0.2350 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.8877   -1.8488    0.0274 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.4081   -2.3046    0.1384 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.6270   -0.6445   -0.0851 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  2  0  0  0  0
  3  2  1  0  0  0  0
  4  5  1  0  0  0  0
  5 10  2  0  0  0  0
  6  7  2  0  0  0  0
  6  5  1  0  0  0  0
  7  8  1  0  0  0  0
  8  9  2  0  0  0  0
 10  9  1  0  0  0  0
 10  2  1  0  0  0  0
 11  4  1  0  0  0  0
 11 13  1  0  0  0  0
 12 11  1  0  0  0  0
 14 11  1  0  0  0  0
 14 15  1  0  0  0  0
 15 20  2  0  0  0  0
 16 15  1  0  0  0  0
 16 17  2  0  0  0  0
 17 18  1  0  0  0  0
 18 19  2  0  0  0  0
 20 19  1  0  0  0  0
  3 21  1  0  0  0  0
  6 22  1  0  0  0  0
  7 23  1  0  0  0  0
  8 24  1  0  0  0  0
  9 25  1  0  0  0  0
 16 26  1  0  0  0  0
 17 27  1  0  0  0  0
 18 28  1  0  0  0  0
 19 29  1  0  0  0  0
  4 30  2  0  0  0  0
 20 30  1  0  0  0  0
  3 30  1  0  0  0  0
M  CHG  2   4   1  11  -1
M  END
$$$$

````
[fixed.zip](https://github.com/mordred-descriptor/mordred/files/10358389/fixed.zip)

**Comment by xiaoboy185** [comment]
@tobigithub Thanks very much, the above fixed sdf is exactly what i want. 
Actually, i am dealing with many many such kind of molecules. 
Now, I have obtained their 3D .xyz files, it there any convenient method to covert the .xyz file to the above fixed .sdf file?
Thanks

**Comment by tobigithub** [comment]
Chemaxon standardizer 
https://docs.chemaxon.com/display/docs/standardizer.md

**Comment by xiaoboy185** [comment]
@tobigithub Thank you very much!

**Comment by f807494659-stack** [comment]
> [@tobigithub](https://github.com/tobigithub)非常感谢！
 
I also encountered the same problem, may I ask how did you solve it in the end, I used the normalizer above and still could not get the correct sdf file
