### ISSUE TITLE
Descriptor coverage

### ISSUE THREAD

**Issue by rgerkin** [mordred-descriptor/mordred#24]
@philopon 
I'm starting to use this for some of my work, but I'm unclear as to how the coverage of Mordred compares to that from some other (often more difficult) options, including:  
- CDK
- rdKit
- Indigo
- PaDEL
- Vega
- Dragon

Do you know -- for each of these packages -- how many descriptors they calculate that aren't in Mordred?  I might be able to help implement some of the ones that aren't.  I'd like to help get this as close to Dragon-level as possible.

**Comment by philopon** [comment]
Thanks for using this software!

Not implemented Descriptor groups are:

* PaDEL/CDK (12/63)
    * 2D
        * ALOGP
        * Crippen logP and MR
        * Largest chain
        * Largest Pi system
        * Largest aliphatic chain
        * Mannhold LogP
        * Molecular linear free energy relation
        * XLogP
    * 3D
        * 3D autocorrelation (#12)
        * Length over breadth (but, CDK implementation of this descriptor is totally buggy from algorithm. 3D Rotating calipers should be used to get this descriptor.)
        * RDF (#13)
        * WHIM (#14)
* rdkit (0/7) - all of rdkit descriptor were wrapped.

I don't use other software. Thus, can't say for certain. I'll check these. Please check [documentation](http://mordred-descriptor.github.io/documentation/master/) or [descriptor list](http://mordred-descriptor.github.io/documentation/master/descriptors.html) for detail.

We are welcome to contribute to this software! Some descriptors that will be implemented were registered to [issue](https://github.com/mordred-descriptor/mordred/issues?q=is%3Aissue+is%3Aopen+label%3Adescriptor). Of course, It is welcome to make issue to request other descriptors.

If you could help this project but you have no descriptor to want use, Mannhold LogP may be able to  implement easily.

MLogP = 1.46 + 0.11 NumberOfCarbons - 0.11 NumberOfHeteroAtoms

We are looking forward to your contribution.

Thanks,

**Comment by philopon** [comment]
detailed comparison table →  https://docs.google.com/spreadsheets/d/1lgVMeiC6rNzFciOhMP7hUzxkwbDa3ug1xmdjNlm4aMU/edit?usp=sharing

**Comment by rgerkin** [comment]
@philopon Thanks for putting this together.
