### ISSUE TITLE
SM1_A, SM1_D

### ISSUE THREAD

**Issue by WhisperWind22** [mordred-descriptor/mordred#40]
Descriptors 'SM1_A', 'SM1_D' are not calculated when calculating through 

`
from mordred import Calculator, descriptors

Calculator(descriptors)
`

**Comment by philopon** [comment]
Thank you for your comment. And I am sorry for causing your confusion.

These descriptors were removed from preset in 9ee6d37.

SM1 is sum of eigenvalues. It is same as trace (sum of diagonal components). Diagonal components of adjacency matrix (_A) and distance matrix (_D) are zero. Thus, SM1_A and SM1_D are provide zero for all structure. Existance of these descriptors cause confusion. From this, it is decided that SM1_A and SM1_D are removed from preset in v1.1.0-beta.

However, SM1_A and SM1_D can calculate:

option1: add descriptors explicitly

```.py
calc = Calculator(descriptors)
calc.register(AdjacencyMatrix("SM1"))
calc.register(DistanceMatrix("SM1"))
```

option2: use descriptor versioning

```.py
calc = Calculator(descriptors, version="1.0.0")
```

Thanks,

**Comment by WhisperWind22** [comment]
Thanks for the answer.
