### ISSUE TITLE
Python 2/3 inconsistency?

### ISSUE THREAD

**Issue by simonbray** [mordred-descriptor/mordred#76]
Hello,
First of all, thanks for your work on this project.
When I run the example code, I get different results depending on the python version. An example with two conda environments:

```
conda create -y --quiet --override-channels --channel mordred-descriptor --channel defaults --channel rdkit --name mordred2 mordred python=2
conda create -y --quiet --override-channels --channel mordred-descriptor --channel defaults --channel rdkit --name mordred3 mordred python=3
```

Then I run the following code based on the example in the README file:

```
from rdkit import Chem
from mordred import Calculator, descriptors
calc = Calculator(descriptors, ignore_3D=True, version="1.1.1")
mol = Chem.MolFromSmiles('C1NC2=CC(=C(C=C2S(=O)(=O)N1)S(=O)(=O)N)Cl')
calc(mol)
```

However, the values returned are different for the two environments above; for example, `calc(mol)[35:40]` gives different results.

**Comment by philopon** [comment]
Thank you for your report!

This behavior is occurred since dict of python2 is not keep order.

I'll fix it soon.
