### ISSUE TITLE
3d descriptors from only atoms and coordinates

### ISSUE THREAD

**Issue by proexcuse** [mordred-descriptor/mordred#99]
Hello,

Is it possible to obtain 3d descriptors from only atoms and XYZ coordinates, without smiles?

I have many XYZ files but no corresponding smiles. 
I tried to automatically produce smiles using xyz2mol, but failed for many molecules. So gave up creating smiles for all the molecules and instead trying to get descriptors from 3d structures.

**Comment by iuhgnor** [comment]
Maybe you can try Open Babel  http://openbabel.org/docs/current/FileFormats/XYZ_cartesian_coordinates_format.html

**Comment by PARODBE** [comment]
Hi,

I have the same doubt. But in your example there aren't code provided. Could you help us with this? Thanks!

**Comment by iuhgnor** [comment]
> Hi,
> 
> I have the same doubt. But in your example there aren't code provided. Could you help us with this? Thanks!

The following code may work

```python
from rdkit import Chem
from openbabel import pybel
from mordred import Calculator, descriptors

def xyz2mol(xyzfile):
    mol = next(pybel.readfile('xyz', xyzfile))
    mol.write('mol', (xyzfile[:-4] + '.mol'), overwrite=True)

xyzfile = 'test.xyz'
molfile = xyzfile[:-4] + '.mol'
xyz2mol(xyzfile)

mol = Chem.MolFromMolFile(molfile, removeHs=False)

calc = Calculator(descriptors, ignore_3D=False)
des = calc(mol)
```

**Comment by proexcuse** [comment]
Thanks a lot for your help!

**Comment by xiaoboy185** [comment]
@iuhgnor Thanks for your message. For some .xyz files, it can not calculate the descriptors, please see attachment.
[test.zip](https://github.com/mordred-descriptor/mordred/files/10367656/test.zip)
[11:49:32] Explicit valence for atom # 11 B, 4, is greater than permitted
[11:49:32] ERROR: Could not sanitize molecule ending on line 68
[11:49:32] ERROR: Explicit valence for atom # 11 B, 4, is greater than permitted
WARNING:root:mol read failure: test.0
How to solve this issue?
Thanks

**Comment by iuhgnor** [comment]
> @iuhgnor Thanks for your message. For some .xyz files, it can not calculate the descriptors, please see attachment. [test.zip](https://github.com/mordred-descriptor/mordred/files/10367656/test.zip) [11:49:32] Explicit valence for atom # 11 B, 4, is greater than permitted [11:49:32] ERROR: Could not sanitize molecule ending on line 68 [11:49:32] ERROR: Explicit valence for atom # 11 B, 4, is greater than permitted WARNING:root:mol read failure: test.0 How to solve this issue? Thanks

Sorry, I have no idea. According to the exception, rdkit found the explicit valence of B atom is +4 and seems not chemically unreasonable (https://github.com/rdkit/rdkit/wiki/FrequentlyAskedQuestions).
